tinymce.addI18n ('en', {
"POWr Plugin":"POWr Plugin",
"Insert POWr Forms":"Insert POWr Forms",
"Popular":"Popular",
"Form Builder":"Form Builder",
"Popup":"Popup",
"Media Gallery":"Media Gallery",
"Social Feed":"Social Feed",
"Multi Slider":"Multi Slider",
"Countdown Timer":"Countdown Timer",
"FAQ":"FAQ",
"Chat":"Chat",
"Ecommerce":"Ecommerce",
"Social Media Icons":"Social Media Icons",
"Price Table":"Price Table",
"Forms & Surveys":"Forms & Surveys",
"Contact Form":"Contact Form",
"Form Builder":"Form Builder",
"Mailing List":"Mailing List",
"Order Form":"Order Form",
"Poll":"Poll",
"Survey":"Survey",
"Galleries & Sliders":"Galleries & Sliders",
"Banner Slider":"Banner Slider",
"Event Gallery":"Event Gallery",
"Event Slider":"Event Slider",
"Flickr Gallery":"Flickr Gallery",
"Image Slider":"Image Slider",
"Media Gallery":"Media Gallery",
"Microblog":"Microblog",
"Multi-Slider":"Multi-Slider",
"Photo Gallery":"Photo Gallery",
"Video Gallery":"Video Gallery",
"Video Slider":"Video Slider",
"Youtube Gallery":"Youtube Gallery",
"Social":"Social",
"Chat":"Chat",
"Comments":"Comments",
"Facebook Feed":"Facebook Feed",
"Instagram Feed":"Instagram Feed",
"Pinterest Feed":"Pinterest Feed",
"Reviews":"Reviews",
"RSS Feed":"RSS Feed",
"Social Feed":"Social Feed",
"Social Media Icons":"Social Media Icons",
"Tumblr Feed":"Tumblr Feed",
"Twitter Feed":"Twitter Feed",
"eCommerce":"eCommerce",
"Ecommerce":"Ecommerce",
"Digital Download":"Digital Download",
"Paypal Button":"Paypal Button",
"Plan Comparison":"Plan Comparison",
"Price Table":"Price Table",
"About Us":"About Us",
"Button":"Button",
"Countdown Timer":"Countdown Timer",
"Count Up Timer":"Count Up Timer",
"Price Table":"Price Table",
"FAQ":"FAQ",
"Graph":"Graph",
"Hit Counter":"Hit Counter",
"Job Board":"Job Board",
"Map":"Map",
"Menu":"Menu",
"Music Player":"Music Player",
"Notification Bar":"Notification Bar",
"Popup":"Popup",
"Resume":"Resume",
"Scroll to Top":"Scroll to Top",
"Tabs":"Tabs",
"weather":"weather",
});